/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#ifndef __cplusplus
#error This file must be compiled as Obj-C++. If you are importing it, you must change your file extension to .mm.
#endif

// Avoid multiple includes of ArcSoftFaceReactNativeSpec symbols
#ifndef ArcSoftFaceReactNativeSpec_H
#define ArcSoftFaceReactNativeSpec_H

#import <Foundation/Foundation.h>
#import <RCTRequired/RCTRequired.h>
#import <RCTTypeSafety/RCTConvertHelpers.h>
#import <RCTTypeSafety/RCTTypedModuleConstants.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTCxxConvert.h>
#import <React/RCTManagedPointer.h>
#import <ReactCommon/RCTTurboModule.h>
#import <optional>
#import <vector>


NS_ASSUME_NONNULL_BEGIN
namespace JS {
  namespace NativeArcsoftFace {
    struct SpecInitEngineOptions {
      NSString *detectMode() const;
      std::optional<double> maxFaceNum() const;
      std::optional<double> scale() const;
      std::optional<bool> enableAge() const;
      std::optional<bool> enableGender() const;
      std::optional<bool> enableLiveness() const;
      std::optional<bool> enable3DAngle() const;

      SpecInitEngineOptions(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeArcsoftFace_SpecInitEngineOptions)
+ (RCTManagedPointer *)JS_NativeArcsoftFace_SpecInitEngineOptions:(id)json;
@end
namespace JS {
  namespace NativeArcsoftFace {
    struct FaceRect {
      double left() const;
      double top() const;
      double right() const;
      double bottom() const;

      FaceRect(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeArcsoftFace_FaceRect)
+ (RCTManagedPointer *)JS_NativeArcsoftFace_FaceRect:(id)json;
@end
namespace JS {
  namespace NativeArcsoftFace {
    struct FaceInfo {
      JS::NativeArcsoftFace::FaceRect rect() const;
      double orient() const;

      FaceInfo(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeArcsoftFace_FaceInfo)
+ (RCTManagedPointer *)JS_NativeArcsoftFace_FaceInfo:(id)json;
@end
namespace JS {
  namespace NativeArcsoftFace {
    struct FaceFeature {
      NSString *dataBase64() const;

      FaceFeature(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeArcsoftFace_FaceFeature)
+ (RCTManagedPointer *)JS_NativeArcsoftFace_FaceFeature:(id)json;
@end
@protocol NativeArcsoftFaceSpec <RCTBridgeModule, RCTTurboModule>

- (void)activateOnline:(NSString *)appId
                sdkKey:(NSString *)sdkKey
               resolve:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject;
- (void)initEngine:(JS::NativeArcsoftFace::SpecInitEngineOptions &)options
           resolve:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject;
- (void)unInitEngine:(RCTPromiseResolveBlock)resolve
              reject:(RCTPromiseRejectBlock)reject;
- (void)detectFacesNV21:(NSArray *)nv21
                  width:(double)width
                 height:(double)height
                resolve:(RCTPromiseResolveBlock)resolve
                 reject:(RCTPromiseRejectBlock)reject;
- (void)extractFeatureNV21:(NSArray *)nv21
                     width:(double)width
                    height:(double)height
                      face:(JS::NativeArcsoftFace::FaceInfo &)face
                   resolve:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject;
- (void)compareFeature:(JS::NativeArcsoftFace::FaceFeature &)f1
                    f2:(JS::NativeArcsoftFace::FaceFeature &)f2
               resolve:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject;
- (void)getAgeNV21:(NSArray *)nv21
             width:(double)width
            height:(double)height
             faces:(NSArray *)faces
           resolve:(RCTPromiseResolveBlock)resolve
            reject:(RCTPromiseRejectBlock)reject;
- (void)getGenderNV21:(NSArray *)nv21
                width:(double)width
               height:(double)height
                faces:(NSArray *)faces
              resolve:(RCTPromiseResolveBlock)resolve
               reject:(RCTPromiseRejectBlock)reject;
- (void)getLivenessNV21:(NSArray *)nv21
                  width:(double)width
                 height:(double)height
                  faces:(NSArray *)faces
                resolve:(RCTPromiseResolveBlock)resolve
                 reject:(RCTPromiseRejectBlock)reject;
- (void)getFace3DAngleNV21:(NSArray *)nv21
                     width:(double)width
                    height:(double)height
                     faces:(NSArray *)faces
                   resolve:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject;
- (void)faceDBAdd:(NSString *)id
          feature:(JS::NativeArcsoftFace::FaceFeature &)feature
          resolve:(RCTPromiseResolveBlock)resolve
           reject:(RCTPromiseRejectBlock)reject;
- (void)faceDBRemove:(NSString *)id
             resolve:(RCTPromiseResolveBlock)resolve
              reject:(RCTPromiseRejectBlock)reject;
- (void)faceDBClear:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject;
- (void)faceDBCount:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject;
- (void)faceDBSearch:(JS::NativeArcsoftFace::FaceFeature &)feature
           threshold:(NSNumber *)threshold
             resolve:(RCTPromiseResolveBlock)resolve
              reject:(RCTPromiseRejectBlock)reject;
- (void)setLogLevel:(double)level
            resolve:(RCTPromiseResolveBlock)resolve
             reject:(RCTPromiseRejectBlock)reject;

@end

@interface NativeArcsoftFaceSpecBase : NSObject {
@protected
facebook::react::EventEmitterCallback _eventEmitterCallback;
}
- (void)setEventEmitterCallback:(EventEmitterCallbackWrapper *)eventEmitterCallbackWrapper;


@end

namespace facebook::react {
  /**
   * ObjC++ class for module 'NativeArcsoftFace'
   */
  class JSI_EXPORT NativeArcsoftFaceSpecJSI : public ObjCTurboModule {
  public:
    NativeArcsoftFaceSpecJSI(const ObjCTurboModule::InitParams &params);
  };
} // namespace facebook::react
inline NSString *JS::NativeArcsoftFace::SpecInitEngineOptions::detectMode() const
{
  id const p = _v[@"detectMode"];
  return RCTBridgingToOptionalString(p);
}
inline std::optional<double> JS::NativeArcsoftFace::SpecInitEngineOptions::maxFaceNum() const
{
  id const p = _v[@"maxFaceNum"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<double> JS::NativeArcsoftFace::SpecInitEngineOptions::scale() const
{
  id const p = _v[@"scale"];
  return RCTBridgingToOptionalDouble(p);
}
inline std::optional<bool> JS::NativeArcsoftFace::SpecInitEngineOptions::enableAge() const
{
  id const p = _v[@"enableAge"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<bool> JS::NativeArcsoftFace::SpecInitEngineOptions::enableGender() const
{
  id const p = _v[@"enableGender"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<bool> JS::NativeArcsoftFace::SpecInitEngineOptions::enableLiveness() const
{
  id const p = _v[@"enableLiveness"];
  return RCTBridgingToOptionalBool(p);
}
inline std::optional<bool> JS::NativeArcsoftFace::SpecInitEngineOptions::enable3DAngle() const
{
  id const p = _v[@"enable3DAngle"];
  return RCTBridgingToOptionalBool(p);
}
inline double JS::NativeArcsoftFace::FaceRect::left() const
{
  id const p = _v[@"left"];
  return RCTBridgingToDouble(p);
}
inline double JS::NativeArcsoftFace::FaceRect::top() const
{
  id const p = _v[@"top"];
  return RCTBridgingToDouble(p);
}
inline double JS::NativeArcsoftFace::FaceRect::right() const
{
  id const p = _v[@"right"];
  return RCTBridgingToDouble(p);
}
inline double JS::NativeArcsoftFace::FaceRect::bottom() const
{
  id const p = _v[@"bottom"];
  return RCTBridgingToDouble(p);
}
inline JS::NativeArcsoftFace::FaceRect JS::NativeArcsoftFace::FaceInfo::rect() const
{
  id const p = _v[@"rect"];
  return JS::NativeArcsoftFace::FaceRect(p);
}
inline double JS::NativeArcsoftFace::FaceInfo::orient() const
{
  id const p = _v[@"orient"];
  return RCTBridgingToDouble(p);
}
inline NSString *JS::NativeArcsoftFace::FaceFeature::dataBase64() const
{
  id const p = _v[@"dataBase64"];
  return RCTBridgingToString(p);
}
NS_ASSUME_NONNULL_END
#endif // ArcSoftFaceReactNativeSpec_H
