/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#import "ArcSoftFaceReactNativeSpec.h"


@implementation NativeArcsoftFaceSpecBase


- (void)setEventEmitterCallback:(EventEmitterCallbackWrapper *)eventEmitterCallbackWrapper
{
  _eventEmitterCallback = std::move(eventEmitterCallbackWrapper->_eventEmitterCallback);
}
@end

@implementation RCTCxxConvert (NativeArcsoftFace_SpecInitEngineOptions)
+ (RCTManagedPointer *)JS_NativeArcsoftFace_SpecInitEngineOptions:(id)json
{
  return facebook::react::managedPointer<JS::NativeArcsoftFace::SpecInitEngineOptions>(json);
}
@end
@implementation RCTCxxConvert (NativeArcsoftFace_FaceRect)
+ (RCTManagedPointer *)JS_NativeArcsoftFace_FaceRect:(id)json
{
  return facebook::react::managedPointer<JS::NativeArcsoftFace::FaceRect>(json);
}
@end
@implementation RCTCxxConvert (NativeArcsoftFace_FaceInfo)
+ (RCTManagedPointer *)JS_NativeArcsoftFace_FaceInfo:(id)json
{
  return facebook::react::managedPointer<JS::NativeArcsoftFace::FaceInfo>(json);
}
@end
@implementation RCTCxxConvert (NativeArcsoftFace_FaceFeature)
+ (RCTManagedPointer *)JS_NativeArcsoftFace_FaceFeature:(id)json
{
  return facebook::react::managedPointer<JS::NativeArcsoftFace::FaceFeature>(json);
}
@end
namespace facebook::react {
  
    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_activateOnline(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "activateOnline", @selector(activateOnline:sdkKey:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_initEngine(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "initEngine", @selector(initEngine:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_unInitEngine(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "unInitEngine", @selector(unInitEngine:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_detectFacesNV21(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "detectFacesNV21", @selector(detectFacesNV21:width:height:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_extractFeatureNV21(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "extractFeatureNV21", @selector(extractFeatureNV21:width:height:face:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_compareFeature(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "compareFeature", @selector(compareFeature:f2:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_getAgeNV21(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "getAgeNV21", @selector(getAgeNV21:width:height:faces:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_getGenderNV21(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "getGenderNV21", @selector(getGenderNV21:width:height:faces:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_getLivenessNV21(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "getLivenessNV21", @selector(getLivenessNV21:width:height:faces:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_getFace3DAngleNV21(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "getFace3DAngleNV21", @selector(getFace3DAngleNV21:width:height:faces:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_faceDBAdd(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "faceDBAdd", @selector(faceDBAdd:feature:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_faceDBRemove(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "faceDBRemove", @selector(faceDBRemove:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_faceDBClear(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "faceDBClear", @selector(faceDBClear:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_faceDBCount(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "faceDBCount", @selector(faceDBCount:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_faceDBSearch(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "faceDBSearch", @selector(faceDBSearch:threshold:resolve:reject:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeArcsoftFaceSpecJSI_setLogLevel(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, PromiseKind, "setLogLevel", @selector(setLogLevel:resolve:reject:), args, count);
    }

  NativeArcsoftFaceSpecJSI::NativeArcsoftFaceSpecJSI(const ObjCTurboModule::InitParams &params)
    : ObjCTurboModule(params) {
      
        methodMap_["activateOnline"] = MethodMetadata {2, __hostFunction_NativeArcsoftFaceSpecJSI_activateOnline};
        
        
        methodMap_["initEngine"] = MethodMetadata {1, __hostFunction_NativeArcsoftFaceSpecJSI_initEngine};
        setMethodArgConversionSelector(@"initEngine", 0, @"JS_NativeArcsoftFace_SpecInitEngineOptions:");
        
        methodMap_["unInitEngine"] = MethodMetadata {0, __hostFunction_NativeArcsoftFaceSpecJSI_unInitEngine};
        
        
        methodMap_["detectFacesNV21"] = MethodMetadata {3, __hostFunction_NativeArcsoftFaceSpecJSI_detectFacesNV21};
        
        
        methodMap_["extractFeatureNV21"] = MethodMetadata {4, __hostFunction_NativeArcsoftFaceSpecJSI_extractFeatureNV21};
        setMethodArgConversionSelector(@"extractFeatureNV21", 3, @"JS_NativeArcsoftFace_FaceInfo:");
        
        methodMap_["compareFeature"] = MethodMetadata {2, __hostFunction_NativeArcsoftFaceSpecJSI_compareFeature};
        setMethodArgConversionSelector(@"compareFeature", 0, @"JS_NativeArcsoftFace_FaceFeature:");
        setMethodArgConversionSelector(@"compareFeature", 1, @"JS_NativeArcsoftFace_FaceFeature:");
        
        methodMap_["getAgeNV21"] = MethodMetadata {4, __hostFunction_NativeArcsoftFaceSpecJSI_getAgeNV21};
        
        
        methodMap_["getGenderNV21"] = MethodMetadata {4, __hostFunction_NativeArcsoftFaceSpecJSI_getGenderNV21};
        
        
        methodMap_["getLivenessNV21"] = MethodMetadata {4, __hostFunction_NativeArcsoftFaceSpecJSI_getLivenessNV21};
        
        
        methodMap_["getFace3DAngleNV21"] = MethodMetadata {4, __hostFunction_NativeArcsoftFaceSpecJSI_getFace3DAngleNV21};
        
        
        methodMap_["faceDBAdd"] = MethodMetadata {2, __hostFunction_NativeArcsoftFaceSpecJSI_faceDBAdd};
        setMethodArgConversionSelector(@"faceDBAdd", 1, @"JS_NativeArcsoftFace_FaceFeature:");
        
        methodMap_["faceDBRemove"] = MethodMetadata {1, __hostFunction_NativeArcsoftFaceSpecJSI_faceDBRemove};
        
        
        methodMap_["faceDBClear"] = MethodMetadata {0, __hostFunction_NativeArcsoftFaceSpecJSI_faceDBClear};
        
        
        methodMap_["faceDBCount"] = MethodMetadata {0, __hostFunction_NativeArcsoftFaceSpecJSI_faceDBCount};
        
        
        methodMap_["faceDBSearch"] = MethodMetadata {2, __hostFunction_NativeArcsoftFaceSpecJSI_faceDBSearch};
        setMethodArgConversionSelector(@"faceDBSearch", 0, @"JS_NativeArcsoftFace_FaceFeature:");
        
        methodMap_["setLogLevel"] = MethodMetadata {1, __hostFunction_NativeArcsoftFaceSpecJSI_setLogLevel};
        
  }
} // namespace facebook::react
